version: '3.4'

services:
  app:
    build: app
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/conf.d/default.conf
    container_name: test-app
    restart: on-failure
    ports:
    - 80:80
